# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
WARNING_FLAGS="-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing"
COMMON_FLAGS="-march=znver5 -O2 -pipe -flto ${WARNING_FLAGS}"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="${COMMON_FLAGS} ${LDFLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

GENTOO_MIRRORS="rsync://mirrors.kernel.org/mirrors/gentoo/"

USE="lto llvm_targets_AMDGPU qt5 kde plasma bluetooth dbus mtp networkmanager multilib offensive opengl screencast symlink udev usb vaapi vulkan wayland bash-completion webengine"

# Overrides the profile's ACCEPT_LICENSE default value
ACCEPT_LICENSE="* -@EULA"

GRUB_PLATFORMS="efi-64"
